contrib/hugo: new package (0.124.1)
chimera-linux/cports pull request #1738
Opened 2024-04-02 21:00 UTC by ifreund

2024-04-02 21:28 UTC, mhmdanas requested changes

2024-04-02 21:28 UTC, mhmdanas commented on contrib/hugo/template.py
> +options = ["!check"]
```suggestion
# tests require network access
# manpages and completions are generated by running binary so no cross
options = ["!check", "!cross"]
```

2024-04-02 21:41 UTC, ifreund commented on contrib/hugo/template.py
> +options = ["!check"]
Added, thanks

2024-04-03 22:43 UTC, nekopsykose commented on contrib/hugo/template.py
> +pkgdesc = "Fast and flexible static site generator"
```suggestion
pkgdesc = "Static site generator"
```

2024-04-05 08:07 UTC, ifreund commented on contrib/hugo/template.py
> +pkgdesc = "Fast and flexible static site generator"
done :)

2024-04-05 08:11 UTC, merged