Add Prism Launcher (7.0) and dependencies
chimera-linux/cports pull request #187
Opened 2023-06-12 13:22 UTC by anellie

This PR adds PrismLauncher, along with 2 build dependencies it needed (qt6-5compat, extra-cmake-modules).
This is my first PR, so I hope I got the templates right, especially since I wasn't sure of a good way to specify the Java installation for PL.
It builds and runs fine on x86; it should too on ARM and PPC but I was unable to test it due to not having any hardware available.

2023-06-12 14:04 UTC, q66 commented
make sure to run your files through `black` and `flake8` ideally beforehand, right now it's not so important as the CI is not loaded significantly, but once there is more stuff it may result in unnecessary stalls

2023-06-12 14:05 UTC, anellie commented
Yeah, will do next time! I admittedly just forgot with these, will fix the formatting and redo the commits.

2023-06-12 14:09 UTC, anellie commented
Should be good to go now! `flake8 contrib` reports no errors. Sorry for the trouble and thanks for the review!

2023-06-12 21:21 UTC, q66 requested changes
looks good otherwise, just please wait a bit until i address the _JAVA_HOME stuff :)

2023-06-12 21:21 UTC, q66 commented on contrib/extra-cmake-modules/template.py
> +makedepends = []
you can remove this one

2023-06-12 21:21 UTC, q66 commented on contrib/extra-cmake-modules/template.py
> +
no need for the empty line here

2023-06-12 21:21 UTC, q66 commented on contrib/prismlauncher/template.py
> +configure_env = {"JAVA_HOME": "/usr/lib/jvm/java-17-openjdk"}
i'll think about this one a bit more if you don't mind

2023-06-12 21:21 UTC, q66 commented on contrib/qt6-5compat/template.py
> +
ditto empty line shouldn't be here

2023-06-13 20:20 UTC, anellie commented
Redid the commits with the requested changes and removed the `JAVA_HOME`, which `java-common`  should handle now. Have not built it yet due to r1 of the JDK not being available as a binary package yet

2023-06-13 20:23 UTC, anellie commented
Weird, it still behaves the same as it did without specifying `JAVA_HOME`... `java_common` should have taken care of doing so, correct?

2023-06-13 20:36 UTC, q66 commented
profile.d is for login shells, package builds don't spawn a login shell

2023-06-13 21:21 UTC, q66 commented
well, just do the configure_env, there is not much point in setting up anything more elaborate

2023-06-13 21:49 UTC, q66 commented
qt6-5compat should be called qt6-qt5compat to follow the existing local and upstream convention, otherwise lgtm

2023-06-13 21:57 UTC, anellie commented
Renamed it now

2023-06-13 21:57 UTC, merged